#Pods use PersistentVolumeClaims to request physical storage.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-claim
  labels:
    app: mongo
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
