apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: myedgegateway.com
    http:
      paths:
      - backend:
          serviceName: mosquitto-service
          servicePort: 1883
        path: /mosquitto
        pathType: ImplementationSpecific
      - backend:
          serviceName: nodered-service
          servicePort: 1880
        path: /nodered
        pathType: ImplementationSpecific
      - backend:
          serviceName: mysql-service
          servicePort: 3306
        path: /mysql
        pathType: ImplementationSpecific
      - backend:
          serviceName: mlflowui-service
          servicePort: 5000
        path: /mlflowui