#Pods use PersistentVolumeClaims to request physical storage.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ml-claim
  labels:
    rioiotplatform: ml
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
