apiVersion: v1
kind: Service
metadata:
  name: ml-pod
  labels:
    rioiotplatform: ml
spec:
  ports:
  - name: 
    protocol: TCP
    port: 8888
    nodePort: 8888
  selector:
    app: ml-pod
  type: nodePort