apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    name: elasticsearch
  name: elasticsearch
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/elasticsearch

spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch
  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g #The flag Xmx specifies the maximum memory allocation pool for a Java virtual machine (JVM), 
                               #while Xms specifies the initial memory allocation pool.
                               #Note: check https://github.com/docker-library/elasticsearch/issues/111 for  virtual memory error 
        image: ind3x/rpi-elasticsearch #docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        ports:
        - containerPort: 9200
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
