#Pods use PersistentVolumeClaims to request physical storage.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  labels:
    app: mysql
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
