#Pod’s configuration file specifies a PersistentVolumeClaim,
#but it does not specify a PersistentVolume.
#From the Pod’s point of view, the claim is a volume.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodered
  labels:
    rioiotplatform: nodered
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - image: rpi-nodered
        imagePullPolicy: Always
        name: nginx
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"
        #env:
        #- name: MYSQL_ROOT_PASSWORD
        #  value: ""
        ports:
        - containerPort: 1880
        #volumeMounts:
        #- mountPath: /var/lib/mysql
        #  name: mysql-volume
      restartPolicy: Always
      #volumes:
      #- name: mysql-volume
      #  persistentVolumeClaim:
      #    claimName: mysql-claim