#Pod’s configuration file specifies a PersistentVolumeClaim,
#but it does not specify a PersistentVolume.
#From the Pod’s point of view, the claim is a volume.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  labels:
    rioiotplatform: nodered
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      nodeName: raspberrypi
      containers:
      - image: nodered/node-red:1.2.0-10-arm32v7
        imagePullPolicy: Always
        name: nodered
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"
        ports:
        - containerPort: 1880
        volumeMounts:
        - mountPath: /data
          name: nodered-volume
      restartPolicy: Always
      volumes:
      - name: nodered-volume
        persistentVolumeClaim:
          claimName: nodered-claim