apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    rioiotplatform: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      nodeName: raspberrypi
      containers:
      - image: eclipse-mosquitto
        imagePullPolicy: Always
        name: mosquitto
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /mosquitto/data
          name: mosquitto-volume
      restartPolicy: Always
      volumes:
      - name: mosquitto-volume
        persistentVolumeClaim:
          claimName: mosquitto-claim
