kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-volume
  labels:
    #type: local
    app: mosquitto
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/mosquitto/"
 