apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  creationTimestamp: null
  labels:
    name: kibana #this specification will create a new Service object named “kibana” 
                 #which targets TCP port 5601 on any Pod with the "name: kibana" label. 
  name: kibana
  selfLink: /api/v1/namespaces/monitoring/services/kibana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32602
    port: 80
    protocol: TCP
    targetPort: 5601
  - name: https
    nodePort: 30676
    port: 443
    protocol: TCP
    targetPort: 5601
  selector:
    name: kibana
  sessionAffinity: None
  type: NodePort
