kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/mosquitto"